"""The tracked peaks: the official 46 (traditional list elevations, ft) plus
4000-footers that don't count. `osm` lists name variants used to find each
summit in OpenStreetMap; `elev` of None means "use the OSM/DEM elevation".
"""

PEAKS = [
    # name, elevation ft, official, osm name variants
    ("Mount Marcy", 5344, True, ["Mount Marcy"]),
    ("Algonquin Peak", 5114, True, ["Algonquin Peak"]),
    ("Mount Haystack", 4960, True, ["Mount Haystack", "Haystack Mountain"]),
    ("Mount Skylight", 4926, True, ["Mount Skylight", "Skylight"]),
    ("Whiteface Mountain", 4867, True, ["Whiteface Mountain"]),
    ("Dix Mountain", 4857, True, ["Dix Mountain"]),
    ("Gray Peak", 4840, True, ["Gray Peak"]),
    ("Iroquois Peak", 4840, True, ["Iroquois Peak"]),
    ("Basin Mountain", 4827, True, ["Basin Mountain"]),
    ("Gothics", 4736, True, ["Gothics", "Gothics Mountain"]),
    ("Mount Colden", 4714, True, ["Mount Colden"]),
    ("Giant Mountain", 4627, True, ["Giant Mountain"]),
    ("Nippletop", 4620, True, ["Nippletop", "Nippletop Mountain"]),
    ("Santanoni Peak", 4607, True, ["Santanoni Peak", "Santanoni Mountain"]),
    ("Mount Redfield", 4606, True, ["Mount Redfield", "Redfield"]),
    ("Wright Peak", 4580, True, ["Wright Peak"]),
    ("Saddleback Mountain", 4515, True, ["Saddleback Mountain"]),
    ("Panther Peak", 4442, True, ["Panther Peak"]),
    ("Table Top Mountain", 4427, True, ["Tabletop Mountain", "Table Top Mountain", "TableTop Mountain"]),
    ("Rocky Peak Ridge", 4420, True, ["Rocky Peak Ridge", "Rocky Peak"]),
    ("Macomb Mountain", 4405, True, ["Macomb Mountain"]),
    ("Armstrong Mountain", 4400, True, ["Armstrong Mountain"]),
    ("Hough Peak", 4400, True, ["Hough Peak"]),
    ("Seward Mountain", 4361, True, ["Seward Mountain"]),
    ("Mount Marshall", 4360, True, ["Mount Marshall"]),
    ("Allen Mountain", 4340, True, ["Allen Mountain"]),
    ("Big Slide Mountain", 4240, True, ["Big Slide Mountain"]),
    ("Esther Mountain", 4240, True, ["Esther Mountain"]),
    ("Upper Wolfjaw Mountain", 4185, True, ["Upper Wolfjaw Mountain", "Upper Wolf Jaw Mountain"]),
    ("Lower Wolfjaw Mountain", 4175, True, ["Lower Wolfjaw Mountain", "Lower Wolf Jaw Mountain"]),
    ("Street Mountain", 4166, True, ["Street Mountain"]),
    ("Phelps Mountain", 4161, True, ["Phelps Mountain"]),
    ("Mount Donaldson", 4140, True, ["Mount Donaldson", "Donaldson Mountain"]),
    ("Seymour Mountain", 4120, True, ["Seymour Mountain"]),
    ("Sawteeth", 4100, True, ["Sawteeth", "Sawteeth Mountain"]),
    ("Cascade Mountain", 4098, True, ["Cascade Mountain"]),
    ("South Dix", 4060, True, ["South Dix", "Carson Peak", "South Dix Mountain"]),
    ("Porter Mountain", 4059, True, ["Porter Mountain"]),
    ("Mount Colvin", 4057, True, ["Mount Colvin"]),
    ("Mount Emmons", 4040, True, ["Mount Emmons", "Emmons Mountain"]),
    ("Dial Mountain", 4020, True, ["Dial Mountain"]),
    ("Grace Peak", 4012, True, ["Grace Peak", "East Dix"]),
    ("Blake Peak", 3960, True, ["Blake Peak", "Blake Mountain"]),
    ("Cliff Mountain", 3960, True, ["Cliff Mountain"]),
    ("Nye Mountain", 3895, True, ["Nye Mountain"]),
    ("Couchsachraga Peak", 3820, True, ["Couchsachraga Peak"]),
    # 4000-footers that aren't on the official list
    ("MacNaughton Mountain", 4000, False, ["MacNaughton Mountain", "Mount MacNaughton"]),
    ("Little Marcy", None, False, ["Little Marcy"]),
    ("Yard Mountain", 4018, False, ["Yard Mountain"]),
    ("Boundary Peak", None, False, ["Boundary Peak"]),
    ("Pyramid Peak", None, False, ["Pyramid Peak"]),
    ("Lookout Mountain", None, False, ["Lookout Mountain"]),
    ("Little Haystack", None, False, ["Little Haystack", "Little Haystack Mountain"]),
]

assert sum(1 for p in PEAKS if p[2]) == 46
